# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Multiverso Geek 1ª Edição"
email: "multiversogeeksm@gmail.com"
description: "O Multiverso Geek está na sua 1ª Edição em Santa Maria"
baseurl: ""
url: "https://multiversogeek.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-128906233-1"
googleAnalyticsSiteUrl: "multiversogeek.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Multiverso Geek"
organizerAlternateName: "Multiverso Geek"
organizerDescription: "Evento geek de Santa Maria."
organizerEmail: "multiversogeeksm@gmail.com"
organizerLogo: "/img/seo/multiverso.png"
organizerLink: "https://www.facebook.com/multiversogeeksm/"

# Head
metaKeywords: "evento, geek, santa maria, multiverso geek"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/multiverso-geek.jpg"
socialImageSrcTwitter: "/img/seo/multiverso-geek.jpg"
socialImageSrcFacebook: "/img/seo/multiverso-geek.jpg"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Página inicial"}
#  - {permalink: "/blog/", text: "Notícias"}
 - {permalink: "/programacao/", text: "Programação"}
 - {permalink: "/atracoes/", text: "Atrações"}
 - {link: "https://www.facebook.com/multiversogeeksm", text: "Página do Facebook"}
 - {link: "https://www.facebook.com/events/1506676309434209/", text: "Evento do Facebook"}
#  - {permalink: "/team/", text: "Equipe"}
#  - {permalink: "/logistics/", text: "Hospedagem"}
#  - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
#  - {link: "https://bit.ly/dfua-c4p", text: "Comprar ingressos"}
  - {permalink: "/#tickets", text: "Comprar ingressos"}
rightNavigationButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Comprar ingressos"}
  - {permalink: "/#tickets", text: "Comprar ingressos"}

# Hero Block
heroImage: "fundo-azul.jpg"
heroTitle: "Multiverso <typeout> 1ª Edição"
eventDate: "10 e 11 de Novembro de 2018"
typeoutTextValues: '"Geek", "", "Nerd", "Séries", "Anime", "Santa Maria"'
typeoutFallback: "Geek"
heroButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Comprar ingressos"}

# About Block
aboutTitle: "Sobre o Multiverso Geek"
aboutBlock:
 - {title: "Evento",
    # image: "conference.jpg",
    text: "O Multiverso Geek é um evento realizado pela Terra X Comics que reúne o público apaixonado pela cultura pop, quadrinhos, mangás, séries de TV, cinema, anime, games e afins." }
 - {title: "Painéis",
    # image: "workshop.jpg",
    text: "Durante todo a duração o auditório é utilizado para uma grande diversidade de painéis, shows e oficinas." }
 - {title: "Atrações",
    # image: "hackathon.jpg",
    text: "Diversas atrações regionais estão no evento, como artistas, escritores, estandes e bandas. Não esqueça de pegar um autógrafo para seu livro/HQ favorita!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
#  - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "14", specialCharacter: "+", info: "horas", detail: "de evento"}
 - {count: "20", specialCharacter: "+", info: "atrações", detail: "de todo o estado"}
 - {count: "7", specialCharacter: "+", info: "ambientes", detail: "além de auditório"}

# Latest News Block
latestNewsTitle: "Últimas notícias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Atrações"
rockstarSpeakersButtonText: "Ver todas as atrações"

# Location Block
locationBlockTitle: "Local"
eventLocationName: "CESMA"
eventLocationLink: "https://www.cesma.com.br/"
eventStreetAddress: "Rua Professor Braga, 55"
eventAddressLocality: "Santa Maria"
eventAddressLocalityRegion: "RS"
eventPostalCode: "97015-530"
eventAddressCountry: "Brasil"
eventStartTime: "2018-11-10T14:00"
eventDoorTime: "14:00"
eventEndTime: "2018-11-11T21:00"
eventPlaceCoordinates: "-29.6885039,-53.8075312"
mapCenterCoordinates: "-29.6885039,-53.8075312"
mapMobileCenterCoordinates: "-29.6885039,-53.8075312"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

venueGalleryTitle: "Mapa do evento"
venueGalleryImages:
  - { big: "hall.jpg", thumb: "hall-thumb.jpg", width: 1024, height: 1024 }
  - { big: "primeiro-andar.jpg", thumb: "primeiro-andar-thumb.jpg", width: 1024, height: 1024 }
  - { big: "segundo-andar.jpg", thumb: "segundo-andar-thumb.jpg", width: 1024, height: 1024 }
  - { big: "terceiro-andar.jpg", thumb: "terceiro-andar-thumb.jpg", width: 1024, height: 1024 }

# Tweets Feed Block
# tweetsFeedImage: "twitter-feed.jpg"
# tweetsFeedTitle: "What's Up?"
# twitterHashTag: "devfest"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Parceiros"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

salePointsTitle: "Pontos de Venda"
salePoints:
 -
   name: "Terra X Comics"
   additionalInfo: "Rua Marechal Floriano Peixoto 730.<br/>Contato: (55) 3029.0766"
 -
   name: "Sebo Camobi"
   additionalInfo: "RST 287, nº 7100, ao lado do posto Ipiranga da Faixa Nova de Camobi.<br/>Contato: (55) 3025.6710 e (55) 99979.0110 (WhatsApp)"
 -
   name: "Domínio Geek"
   additionalInfo: "Avenida Nossa Senhora Medianeira, 1321, Loja 26, Trevicenter.<br/>Contato: (55) 99687.8084"
 -
   name: "Lends Club Tabuleiria"
   additionalInfo: "Rua Duque de Caxias, 1074.<br/>Contato: (55) 3307.6248"
 -
   name: "Empório Urbano"
   additionalInfo: "Mercado Público de Santa Maria, Estação da Gare.<br/>Contato: (55) 98469.2452 e (41) 98470.1033 (Whatsapp)"
 -
   name: "Pa-Kua"
   additionalInfo: "Rua Marechal Floriano Peixoto 904, Segundo Andar, Sala 4.<br/>Contato: (55) 3095.0135"

# Tickets Block
ticketsTitle: "Ingressos"
ticketsInfo: "Os ingressos garantem a entrada no evento e todas as atrações no auditório."
ticketsOffers:
 -
  name: "1 dia (Antecipado)"
  price: "R$ 10"
  priceCurrency: ""
  ticketsNumber: "100"
  ribbon: "-25%"
  buyButtonLink: {permalink: "/#salepoints"}
  buyButtonText: "Pontos de venda"
  ticketContentList: ["Entrada e eventos no auditório", "Válido para um dia"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: false
 -
  name: "Combo 2 dias (Antecipado)"
  price: "R$ 15"
  priceCurrency: ""
  ticketsNumber: "150"
  ribbon: "-50%"
  featured: true
  buyButtonLink: {permalink: "/#salepoints"}
  buyButtonText: "Pontos de venda"
  ticketContentList: ["Entrada e eventos no auditório", "Válidos para os 2 dias do evento", "Metade do valor "]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
  disabled: false
 -
  name: "Na Hora (1 dia)"
  price: "R$ 15"
  priceCurrency: ""
  ticketsNumber: "50"
  # buyButtonLink: "http://dfua.ticketforevent.com/"
  # buyButtonText: "Buy Now"
  # additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Entrada e eventos no auditório", "Válido para um dia apenas", "Somente na hora"]
  # validFrom: "2014-08-20T10:00"
  # validThrough: "2014-10-23T23:59"
  venueOnly: true
  disabled: true
  # soldOut: true
  # soldOutText: "Sold Out"

# Footer
socialLinks:
#  - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
#  - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://www.facebook.com/multiversogeeksm", icon: "facebook"}
#  - {permalink: "/feed.xml", icon: "rss"}
# footerBlocks:
#  -
#   title: "Links"
#   links:
#    - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
#    - {link: "https://developers.google.com", text: "Google Developers"}
#  -
#   title: "Contacts"
#   links:
#    - {link: "mailto:lviv@gdg.org.ua", text: "lviv@gdg.org.ua"}
#  -
#   title: "FAQ"
#   links:
#    - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Últimas notícias"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "-29.6885039,-53.8075312"
logisticsMapMobileCenterCoordinates: "-29.6885039,-53.8075312"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
